trigger: none

variables:
  PythonVersion: '3.6'

jobs:
  - job: 'Generate_Individual_Package_Documentation'

    variables:
      skipComponentGovernanceDetection: true
    
    timeoutInMinutes: 120

    pool:
      vmImage: 'ubuntu-18.04'

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(PythonVersion)'
        inputs:
          versionSpec: '$(PythonVersion)'

      - script: |
          pip install --index-url 'https://:2022-04-28T16:06:25.966416Z@time-machines-pypi.sealsecurity.io/' -r eng/ci_tools.txt
        displayName: 'Prep Environment'

      - task: PythonScript@0
        displayName: 'Generate Docs'
        inputs:
          scriptPath: 'scripts/devops_tasks/setup_execute_tests.py'
          arguments: >-
            "$(BuildTargetingString)"
            --toxenv=sphinx

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'documentation' 
          targetPath: '$(Build.SourcesDirectory)/_docs'